name: Linux

on:
  push:
    branches: [ main ]
    tags:
      - '*'
env:
  APP_NAME: dev-search-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create build time info
      id: buildinfo
      shell: bash
      run: | 
        echo "##[set-output name=sha;]$(echo ${GITHUB_SHA})"
        echo "##[set-output name=version;]$(echo $GITHUB_REF | cut -d / -f 3)"
        echo "##[set-output name=time;]$(echo $(date))"
    - name: imprint buildinfo
      run: |
        sed -i "s/##VERSION##/${{ steps.buildinfo.outputs.version }}/g" 'src/main/java/dk/stonemountain/business/ui/Version.java'
        sed -i "s/##BUILD_TIME##/${{ steps.buildinfo.outputs.time }}/g" 'src/main/java/dk/stonemountain/business/ui/Version.java'
        sed -i "s/##SHA##/${{ steps.buildinfo.outputs.sha }}/g" 'src/main/java/dk/stonemountain/business/ui/Version.java'
    - name: print buildinfo in file
      run: cat 'src/main/java/dk/stonemountain/business/ui/Version.java'
    - uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        graalvm: '22.0.0.3-Final'
        jdk: 'java17'
    - run: java -version
    - name: Update apt cache
      run: sudo apt update
    - name: Install libraries
      run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
    - name: Make dist directory
      run: mkdir dist
    - name: Build native with Gradle
      run: ./gradlew -s build nativeCompile nativeLink -Pversion=${{ steps.buildinfo.version }} 
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}
    - run: cp build/gluonfx/x86_64-linux/dev-search-ui dist
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }} 
        path: dist